name: 编译内核a12-5-10

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  push:
    paths:
      - .github/workflows/build-kernel-a12-5-10.yml  # Runs when this workflow file is updated\
  workflow_dispatch:
    inputs:
      # kernelsu_variant:
      #   # description: "选择 KernelSU | 注意:选中MKSU时为标准版"
      #   description: "选择 KernelSU"
      #   required: true
      #   default: SukiSU
      # kernelsu_branch:
      #   description: "选择 ksu 分支"
      #   required: true
      #   type: choice
      #   options:
      #     - Stable(标准)
      #     - Dev(开发)
      #     - Other(其他/指定)
      #   default: Dev(开发)
      # kernelsu_branch_other:
      #   description: "如果选择了 “其他”，请指定您的自定义分支"
      #   required: false
      #   type: string  # This input is required if 'Other' is chosen
      version:
        description: '自定义版本名(如5.10.198后面的字符/留空则使用默认版本号)'
        required: false
        type: string
      use_zram:
        description: '是否开启增加更多ZRAM算法?'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: '是否开启KPM功能?'
        required: true
        type: boolean
        default: true
jobs:
  build-kernel-a12-5-10:
    uses: ./.github/workflows/kernel-a12-5.10.yml
    secrets: inherit
    with:
      make_release: false
      # kernelsu_variant: ${{ inputs.kernelsu_variant }}
      # kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}